### ISSUE TITLE
Feature Request (Maybe?) - Voice per Conversation Agent

### ISSUE THREAD

**Issue by mkammes** [m50/ha-fallback-conversation#11]
I love this add-on. Thank you so much!

(lots of edits)

Is it possible to use a certain voice for Primary Conversation Agent responses, and a certain voice when a failover Agent e.g. Extended OpenAI Conversation, etc is used?

Thanks again!

**Comment by m50** [comment]
Unfortunately, this would not be possible, as the voices are defined at a pipeline level. All the agent does is takes input and provides output in text. The rest of the pipeline then converts the text provided by this agent and converts it into voice.
