### ISSUE TITLE
Home Assistant responded with: Not any

### ISSUE THREAD

**Issue by Ricardo-Miguel-Caldeira** [m50/ha-fallback-conversation#12]
I can't make the fallback work... 
Whenever for a general knowledge question the answer I always get: 

`
Home Assistant responded with: Not any
`

![Fallback](https://github.com/m50/ha-fallback-conversation/assets/52119136/2aefab69-94b0-48e8-bc0b-b3d469582516)

![image](https://github.com/m50/ha-fallback-conversation/assets/52119136/f9a2188e-717a-4085-a2c0-87c5331782b4)

Great project and idea! Thank you for your work!

**Comment by m50** [comment]
That's interesting. It appears that the Home Assistant agent itself is trying to respond to it.

I am able to recreate this myself, but I'm not sure why it's happening. I'll have to look more into it. It appears to be for any question that starts with "Who is...". Repeating the question as "What is..." makes it forward properly.

What I've noticed is that the `response_type` is normally "action_done", but in this case is "query_answer".

If I had to take a guess, there is a built in intent that is triggering on "Who is [name]", but doesn't really seem to be working as I'd expect (Why does it response with just "Not any", even if you ask about a user on the same system?).

This could be a quirk we could work around, but obviously the workaround would likely only work in English. Testing it in Dutch, it does the same thing (returns "Geen"). However, in German for some reason it passed to ChatGPT correctly. In Spanish it also properly passed to ChatGPT.

Possibly it is a work in progress or partially completed (or possibly scrapped?) built-in Intent, that only has Dutch and English defined? Not sure.

I'll have to look further into this

**Comment by freakshock88** [comment]
Might be this intent:
https://github.com/home-assistant/intents/blob/main/sentences/en/person_HassGetState.yaml

**Comment by m50** [comment]
That's almost definitely the problem intent. That is frustrating. The intent would likely need to be modified to fix it.

**Comment by m50** [comment]
I implemented a fix in v1.0.4. Can you upgrade and confirm it is fixed for you?

Please note: The only languages that I know this is an issue in is English and Dutch. If anyone knows what the response would look like in other languages, you can create a PR with updating the `STRANGE_RESPONSES` constant.
