### ISSUE TITLE
Issues detecting error from built in OpenAI Agent

### ISSUE THREAD

**Issue by m50** [m50/ha-fallback-conversation#13]
The built in OpenAI agent seems to return an error, but it isn't detected by the Fallback Agent. Switching to Extended OpenAI Agent seems to work just fine.

See https://community.home-assistant.io/t/ask-openai-questions-from-your-default-conversation-agent/594943/37

**Comment by privx-de** [comment]
It would be great if the default OpenAI agent worked. Since the last update, it can execute Home Assistant voice commands without any additional configuration, so it would be the perfect backup agent if you don't get the sentence just right.

**Comment by m50** [comment]
Hi @privx-de, can you update to the latest version of the conversation agent (1.0.3) and see if you are still experiencing issues?

I updated to v1.0.3, and now I can no longer recreate the issue.

**Comment by m50** [comment]
Going to close this, as if there is any remaining issues, it's likely covered by #17
