### ISSUE TITLE
Use ConversationAgentSelector instead of a custom select

### ISSUE THREAD

**Issue by t0bst4r** [m50/ha-fallback-conversation#2]
In order to select the primary and fallback agents, the options Flow uses a custom list in its schema to show a dropdown with all available agents. The list of existing agents is created based on their names (which are not unique). 

Instead the built-in ConversationAgentSelector could be used. It creates a dropdown with all available agents out of the box and also shows an „edit“ button next to the dropdown to jump directly into the selected agent’s config.

**Comment by m50** [comment]
Yeah, knowing about that, I definitely would like to get this change implemented.

I might make the changes I want to make to config in 2 separate PRs, though I will happily accept a PR as well :)

**Comment by m50** [comment]
Implemented in #3
