### ISSUE TITLE
When use Google GenAI as primary agent, never have case falls back to 2nd agent.

### ISSUE THREAD

**Issue by itispip** [m50/ha-fallback-conversation#23]
What's the condition of falling back? As subject, Google GenAI will never fall back.

**Comment by m50** [comment]
It falls back on failure. The Google AI will not fail except in extreme circumstances, so of course it won't ever fall back.

The use case of this is to have the built-in HomeAssistant as the primary, as it has a lot of failure cases, then have an AI as the secondary which has very few failure cases, so as to reduce your bill/usage of the AI APIs.
