### ISSUE TITLE
[Feature request] Add triggers/hooks/logic

### ISSUE THREAD

**Issue by shaiger** [m50/ha-fallback-conversation#24]
It would be great if there would be some way to force a fallback and even trigger automations based on RegEx/flexible conditions. 
This way even if an LLM claims to be successful, a fallback can be forced (even if not always).
As a sub feature, response chaining can also be supported this way. So the opposite of a fallback.
Today I use an LLM for adding a "personality touch" and on-device for actions. But I need to rely on sentence triggers, which is not very flexible.

**Comment by m50** [comment]
Due to Home Assistant implementing this functionality internally, I will no longer be maintaining this. Sorry
