### ISSUE TITLE
"Not any" can sometimes be a valid answer

### ISSUE THREAD

**Issue by jeffc** [m50/ha-fallback-conversation#27]
In [const.py](https://github.com/m50/ha-fallback-conversation/blob/c066e5cb7a28202f38850a803f80596dab843312/custom_components/fallback_conversation/const.py#L17), `not any` is tagged as a "strange error response" and thus treated as an error. This led to a lot of head-scratching when the query "what lights are on?" (which Home Assistant handles correctly with the response `not any` when no lights are on) was falling through to my fallback agent.

I know this was meant as a workaround for #12, but it seems to be causing bugs of its own. It's not the end of the world, but is probably worth investigating deeper.

**Comment by m50** [comment]
"Not any" is such a very bad response, god this is frustrating. One of the two issues will need to take priority, because unfortunately, both isn't possible with the state of things in Home Assistant...

**Comment by m50** [comment]
Due to Home Assistant implementing this functionality internally, I will no longer be maintaining this. Sorry
