### ISSUE TITLE
No intents were loaded for language: *

### ISSUE THREAD

**Issue by kbromer** [m50/ha-fallback-conversation#29]
Having the same issue as @maxi1134 on issue #26.  The original Home Assistant agent isn't actually loaded (I have Fallback properly configured and going from HA->OpenAI).  Even with things HA understands and OpenAI doesn't, I receive no matched intent - this is a new issue that arose, it was working fine pre-update.  Like the logged issue, I get this error in my logs: 

Logger: homeassistant.components.conversation.default_agent
Source: components/conversation/default_agent.py:229
integration: Conversation (documentation, issues)
First occurred: 5:30:10 PM (10 occurrences)
Last logged: 5:36:50 PM
No intents were loaded for language: *

              I am on 2.0.0;

I reinstalled, Restarted, REmoved and re-added the integration.

I still get: Home Assistant failed with response: Sorry, I couldn't understand that  for basic requests

![image](https://github.com/user-attachments/assets/b86ead23-1550-425d-beed-560a653a3852)

HA logs show: 
```
2024-09-17 11:21:07.193 WARNING (MainThread) [homeassistant.components.conversation.default_agent] No intents were loaded for language: *
```

_Originally posted by @maxi1134 in https://github.com/m50/ha-fallback-conversation/issues/26#issuecomment-2356219479_

**Comment by zSprawl** [comment]
I'm seeing this error as well, but it also shows this message in the logs one time, before showing the above each time you attempt to use the voice control.

```
Logger: homeassistant.components.conversation.default_agent
Source: components/conversation/default_agent.py:697
integration: Conversation ([documentation](https://www.home-assistant.io/integrations/conversation), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+conversation%22))
First occurred: 9:11:26 PM (1 occurrences)
Last logged: 9:11:26 PM
Unable to find supported language variant for *
```

**Comment by m50** [comment]
Interesting. I did make a change to the language thing, thinking I was just cleaning things up, but maybe I accidentally changed functionality since it had been a while since I looked at the code. I'll take a look

**Comment by m50** [comment]
Latest release v2.0.1 will fix it. Just need to edit your voice assistant and resave it to give it it's language back.
