### ISSUE TITLE
Related Issue

### ISSUE THREAD

**Issue by janstadt** [m50/ha-fallback-conversation#33]
I posted this [issue](https://github.com/AlexxIT/StreamAssist/issues/51) in the StreamAssist repo but i am curious if its related to something that is missing in fallback?

This chunk of [code](https://github.com/AlexxIT/StreamAssist/blob/main/custom_components/stream_assist/core/__init__.py#L96-L103) is expecting a wake word engine or speech to text but it apparently doesnt exist when i assign a fallback conversation entity as the assistant in Stream assist.

Curious if you'd be able to take a look or have any ideas? TIA

**Comment by m50** [comment]
It looks like it's looking for the WakeWord from the pipeline, so shouldn't be related to fallback conversation agent at all.

I am not familiar with StreamAssist, or what it does, so I am not sure I know enough to know what may be breaking. From the code, it looks like it's supposed to be based on your pipeline. You may want to look at how your pipelines are configured first.
