### ISSUE TITLE
No Control only for ChatGPT

### ISSUE THREAD

**Issue by Thorsten2605** [m50/ha-fallback-conversation#34]
Hi,

First of  all thank you very much for your efforts and the great integration! 

But if I set up ChatGPT to no control (my intention was to reduce the tokens), Home Assistants Voice Assistant can't control either anything.

Is it possible to change so the inbuilt Assistant can control device but not the fallback agent?

**Comment by m50** [comment]
What version are you on? v2.0.1 should fix this, but you will need to re-save your voice assistant entry

**Comment by Thorsten2605** [comment]
I have v2.0.0 installed. But HACS doesn't display any new version...

Edit:
I installed it manually and it seems to work. Thank you very much!
But I wonder why HACS isn't inform me about a new version...

**Comment by m50** [comment]
I cannot explain why HACS wasn't showing the new version, as it does for me... Sorry. But glad it works now for you!
