### ISSUE TITLE
ha-fallback-conversation response

### ISSUE THREAD

**Issue by steamboy23** [m50/ha-fallback-conversation#38]
it's possible to make the fallback agent not respond?  instead of "Home Assistant responded with:" Just nothin'?

**Comment by m50** [comment]
Not sure I fully understand what you mean?

If you have debugging turned off, and your downstream conversation agent doesn't respond with anything, it shouldn't return anything either.

**Comment by steamboy23** [comment]
Yes, that was exactly what I looking for. Turning off debugging solves it. Thank you
