### ISSUE TITLE
[Feature request] make an option Already run the failback before default gives error.

### ISSUE THREAD

**Issue by Bram-diederik** [m50/ha-fallback-conversation#40]
Heya Im dutch and the home assistant error time out takes a way longer time than English. 12 (dutch) vs 3 (English) seconds if no result is found for a simple none existing command like foobar. 

If you pick a none house controlling fallback you can already run the fallback and ditch it if the default gives a positive result. 

So if the  main assist pipeline gives a negative command you save time.

**Comment by m50** [comment]
You mean run them simultaneously, and basically use whatever responds first?

Thing is, the point of this was to reduce calls (and thus reduce cost) to AI (which would be the fallback). This defeats that purpose, as you are making the call, and then potentially not even using it.

At that point, you may as well just use whatever your fallback is.

**Comment by Bram-diederik** [comment]
No only use the failback already running query if the default give no awnser.

I run a local llm on a cpu only system takes some time. But its cheap.

**Comment by shaiger** [comment]
To add to that, in case of fallback the latency can be significant. Latency is anyways rather problematic, as it seems like STT, LLM/Actions and finally TTS are all sequential in the current HA design.
My use of the fallback functionality is very different. The costs for certain LLMs has become rather low, so it is not about saving costs at all. 

What I do is use the LLM for the following:
1. As means to respond to informational or open ended queries that don't have pre-configured sentences (this will still require that the non-LLM options will give it a go, even if just to validate that there is no sentence handler)
2. As real fallback if sentence recognition fails or the exact sentence format was not provided

Perhaps consider the following options:
1. If to run in parallel or in sequence
2. If to use the first that responds, or use the LLM only upon failure

These options can provide a lot of flexibility even when standard HA is not even used. Additional use-cases that can be satisfied with one shot:
1. Let the fastest LLM win
2. Use a smaller model (tuned, flash, o, etc) that may even be local as the backup of a larger model that is more capable and creative. This option will be even better if the LLM would be good at declaring failure, but even by handling network failures there should be benefits.

**Comment by m50** [comment]
Due to Home Assistant implementing this functionality internally, I will no longer be maintaining this. Sorry
