### ISSUE TITLE
Very slow response from LLM (tested with OpenAi and Google)

### ISSUE THREAD

**Issue by vhamburger** [m50/ha-fallback-conversation#43]
Hi, 
i really like the capability of this implementation, but in my case the LLM takes always between 10 - 15 seconds to answer. When calling the llm directly I am down to 1 sec or slightly under.
Contrary, when home assistant can take the call it is lightning fast (under 500ms). Is there a way to tweak the timeout? 10 seconds is painfully long when waiting for an answer or a smarthome action…

**Comment by m50** [comment]
Due to Home Assistant implementing this functionality internally, I will no longer be maintaining this. Sorry
